[package]
name = "musiq"
version = "0.2.4"
edition = "2024"

[features]
debug-access = []
use-encoding = []

[dependencies]
cpal = "0.16.0"
minimp3 = "0.6.1"
rand = "0.9.2"

[build-dependencies]
brotli = "8.0.2"