[package]
name = "musiq"
version = "0.3.2"
edition = "2024"

[features]
debug-access = []
use-encoding = ["dep:brotli"]
only-local = []

[dependencies]
cpal = "0.16.0"
minimp3 = "0.6.1"
rand = "0.9.2"

[build-dependencies]
brotli = { version = "8.0.2", optional = true }